apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset1
  labels:
    app: traffic-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: busybox-container
          image: busybox
          command: ["sh", "-c", "while true; do sleep 3600; done"]
          ports:
            - containerPort: 80

